version: '3'

services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: always
    networks:
      - public-net
    ports:
      - 8005:8000
      - 9000:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro      
      - ./portainer:/data


        
networks:
  public-net:
    external: true
    name: public-net


