---
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    networks:
      - public-net
    environment:
      - PUID=1000
      - PGID=984
      - TZ=Asia/Dhaka
      - DB_CONNECTION=sqlite
      - APP_KEY= #optional
      - DB_HOST= #optional
      - DB_PORT= #optional
      - DB_DATABASE= #optional
      - DB_USERNAME= #optional
      - DB_PASSWORD= #optional
    volumes:
      - ./config:/config
    ports:
      - 5487:80
    restart: unless-stopped

networks:
  public-net:
    external: true
    name: public-net
