version: '2'
services:
  app:
    container_name: filestash
    image: machines/filestash
    restart: always
    environment:
      - APPLICATION_URL=192.168.0.120:7334
    # - GDRIVE_CLIENT_ID=<gdrive_client>
    # - GDRIVE_CLIENT_SECRET=<gdrive_secret>
    # - DROPBOX_CLIENT_ID=<dropbox_key>
    # - ONLYOFFICE_URL=http://onlyoffice
    ports:
    - 7334:8334
    volumes:
    - filestash:/app/data/state/
    # do not expose file system to the internet !
    # labels:
    #   - traefik.enable=true
    #   # https
    #   - traefik.http.routers.filestash.rule=Host(`${duck}`)
    #   - traefik.http.routers.filestash.entrypoints=websecure
    #   - traefik.http.routers.filestash.tls=true
    #   - traefik.http.services.filestash.loadbalancer.server.port=8334
    #   # http
    #   - traefik.http.routers.filestash-insecure.rule=Host(`${duck}`)
    #   - traefik.http.routers.filestash-insecure.entrypoints=web

  # onlyoffice:
  #   container_name: filestash_oods
  #   image: onlyoffice/documentserver
  #   restart: always
  #   security_opt:
  #     - seccomp:unconfined

volumes:
    filestash: {}
