version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - public-net
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    volumes:
      - ./traefikConf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro      


networks:
  public-net:
    external: true
    name: public-net

