version: '3'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - public-net
    restart: unless-stopped    
    depends_on:
      - dockerproxy
    ports:
      - 1011:3000
    environment:
      - PUID=$(UID)
      - PGID=$(GID)
      - TZ=Asia/UTC      
      - HOMEPAGE_VAR_PAIRDROP=${HOMEPAGE_VAR_PAIRDROP}
      - HOMEPAGE_VAR_JELLY=${HOMEPAGE_VAR_JELLY}
      - HOMEPAGE_VAR_NAVI=${HOMEPAGE_VAR_NAVI}
      - HOMEPAGE_VAR_WATCH=${HOMEPAGE_VAR_WATCH}
      - HOMEPAGE_VAR_TRANS_USER=${USER_TRANS}
      - HOMEPAGE_VAR_TRANS_PASS=${USER_PASS_TRANS}
      - HOMEPAGE_VAR_UPTIME_ROBOT_API=${UPTIME_ROBOT_API}
      - HOMEPAGE_VAR_RADARR=${RADARR_API}
      - HOMEPAGE_VAR_SONARR=${SONARR_API}
      - HOMEPAGE_VAR_PROWLARR=${PROWLARR_API}
    volumes:
      - ./config/:/app/config # Make sure your local config directory exists
      - /home:/home:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations 
    labels:
      - "traefik.enable=true"  
      # http
      - "traefik.http.routers.homepage.rule=Host(`${duck}`, `${local_ip}`, `${public_ip}`, `${ngrok}`) && (PathPrefix(`/homepage`) || PathPrefix(`/api`) || PathPrefix(`/_next`) || PathPrefix(`/site.webman`) || PathPrefix(`/android-chrome`) || PathPrefix(`/framework`))"
      - "traefik.http.routers.homepage.entrypoints=web"
      - "traefik.http.middlewares.homepage-strip.stripprefix.prefixes=/homepage"
      - "traefik.http.routers.homepage.middlewares=homepage-strip"
      # https
      - "traefik.http.routers.homepage-secure.rule=Host(`${duck}`, `${public_ip}`, `${ngrok}`) && (PathPrefix(`/homepage`) || PathPrefix(`/api`) || PathPrefix(`/_next`) || PathPrefix(`/site.webman`) || PathPrefix(`/android-chrome`) || PathPrefix(`/framework`))"
      - "traefik.http.routers.homepage-secure.entrypoints=websecure"
      # homepage-strip is set in http route
      - "traefik.http.routers.homepage-secure.middlewares=homepage-strip"
      - 'traefik.http.routers.homepage-secure.tls=true'            
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"    


  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    networks:
      - public-net
    environment:
    - CONTAINERS=1 # Allow access to viewing containers
    - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
    - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
    - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
    - 127.0.0.1:2375:2375
    # environment:
    #   - CONTAINERS=1 # Allow access to viewing containers
    #   - POST=0 # Disallow any POST operations (effectively read-only)
    # ports:
    #   - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped


networks:
  public-net:
    external: true
    name: public-net
