
version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower  
    restart: unless-stopped
    networks:
      - public-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_HTTP_API_TOKEN: "A#YU6!z%eKXrX8"
      WATCHTOWER_HTTP_API_METRICS: "true"
      WATCHTOWER_RUN_ONCE: "false"
      WATCHTOWER_SCHEDULE: "0 9 * * *"
      WATCHTOWER_NOTIFICATION_REPORT: "true" 
      WATCHTOWER_NOTIFICATION_URL: ${watch_discord}
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- with .Report -}}
          {{- if or .Updated .Failed -}}
            {{- range .Updated -}}
        - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
            {{- end -}}
            {{- range .Failed -}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- end -}}


        
networks:
  public-net:
    external: true
    name: public-net


