version: '3'

services:
  couchdb:
    image: apache/couchdb:3.3.2
    container_name: couchdb  
    networks:
      - public-net
    ports:
      - 5984:5984
    volumes:
      - ./couchdb/:/opt/couchdb/data
    restart: always
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}

networks:
  public-net:
    external: true
    name: public-net

