
version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - public-net
    environment:
      - PUID=$(UID)
      - PGID=$(GID)
      # - JELLYFIN_PublishedServerUrl=http://192.168.0.120:8096
      # - TZ=Asia/Dhaka
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ~/storage/public:/media
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0    
    labels:
      - "traefik.enable=true"  
      # https
      - "traefik.http.routers.jellyfin.rule=Host(`${duck}` , `${ngrok}` ,`${public_ip}`, `${local_ip}`) && PathPrefix(`/movie`)"      
      - "traefik.http.routers.jellyfin.entrypoints=websecure"      
      - 'traefik.http.routers.jellyfin.tls=true'      
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      # http
      - "traefik.http.routers.jellyfin-insecure.rule=Host(`${duck}` , `${ngrok}`,`${public_ip}`, `${local_ip}`) && PathPrefix(`/movie`)"      
      - "traefik.http.routers.jellyfin-insecure.entrypoints=web"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

networks:
  public-net:
    external: true
    name: public-net
