version: '3'

services:
  weaviate-obsidian:
    container_name: weaviate-obsidian
    depends_on:
      # - t2v-transformers-obsidian
      - contextionary
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.4
    ports:
    - 3636:8080
    volumes:
      - ./weaviate-data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      DISK_USE_READONLY_PERCENTAGE: 95 # use this if you have used your storage more then 80%. weaviate go read only mode if you have used more then 80% storage used 
      DISK_USE_WARNING_PERCENTAGE: 95
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      # TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers-obsidian:8080'
      # DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      # ENABLE_MODULES: 'text2vec-transformers'
      CLUSTER_HOSTNAME: 'node1'
      CONTEXTIONARY_URL: contextionary:9999
      ENABLE_MODULES: 'text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'


  # t2v-transformers-obsidian:
  #   container_name: t2v-transformers-obsidian
  #   image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
  #   restart: unless-stopped
  #   environment:
  #     ENABLE_CUDA: '0'

  # for light weight model (preferable if you are using cpu)
  contextionary:
    container_name: contextionary-obsidian
    restart: always
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate-obsidian:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
    - 9999:9999




