version: '3'

services:
  yaade:
    restart: unless-stopped
    networks:
      - public-net
    ports:
      - 9339:9339
    environment:
      - YAADE_ADMIN_USERNAME=admin
    volumes:
      - ./yaade:/app/data
    container_name: yaade
    image: esperotech/yaade:latest

networks:
  public-net:
    external: true
    name: public-net

